apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      # Configure Busybox init container configured that repeatedly check's for MySQL container to be up and running . This ensure's that MySQL container online first and then the usermgmt container is brought online as it references the MySQL container to start without any issues 
      initContainers: 
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: usermgmt-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "dbadmin"            
            # Configure k8s secrets from secrets.yaml file 
            - name: DB_PASSWORD 
              valueFrom: 
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password

          # Configure liveness probe that checks if the container is up and running using shell command
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8095
            initialDelaySeconds: 60 # Difference (in seconds) between container start and liveness probe triggered / in use 
            periodSeconds: 10       # How often (in seconds) liveness probe should be executed after the initial delay

          # Configure readiness probe that checks if the container is ready to accept traffic
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10   

          # # Define requests and limits [ optional ]
          # resources:
          #   requests:
          #     memory: "128Mi" # 128 MebiByte is equal to 135 Megabyte (MB)
          #     cpu: "500m" # `m` means milliCPU
          #   limits:
          #     memory: "500Mi"
          #     cpu: "1000m"  # 1000m is equal to 1 VCPU core          
          
                                          
          


        